### PR TITLE
Nomnomnom

### PR DESCRIPTION
**Pull request by raymondben**
See https://github.com/AustralianAntarcticDivision/SOmap/issues/6. Now is probably a good time to merge this into master if we want this to be the new way of the SOmap world.

### CODE REVIEW

**Comment by raymondben** [comment]
I *think* that the test failures are mismatches in the vdiff tests (do the vdiff reference images need to be regenerated?). But I haven't looked further.

**Comment by Maschette** [comment]
They probably do need to be regenerated. We have made a few changes recently. 
Also I suggest once we are happy with Nomnomnom and remerge it to master we go to V1.4.00 (or maybe V2?) These changes provide some serious changes to the package.

**Comment by mdsumner** [comment]
Feel free to zap the vdiffr stuff, comment it out and I'll revisit

**Comment by raymondben** [comment]
I skipped the `vdiffr` tests for the time being, and put this branch version at 0.2.0.

**Comment by Maschette** [comment]
Hey Ben,
There is a conflict in the SOmap.r file that needs to be resolved before I merge them.

**Comment by raymondben** [comment]
Fixed the conflicts, just a couple of lines of code somehow got out of sync between branches.

**Comment by Maschette** [comment]
Great; I will finish up the couple of things I am working on and merge them.

**Pull request merged**
